import Head from "next/head";
import AnalysisTable from "../components/table/AnalysisTable";
import HourlyChart from "../components/table/HourlyChart";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Covid19 Analysis System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>Covid19 Analysis System</h1>
        </header>

        <section className={styles.section}>
          <AnalysisTable id="table" />
          <HourlyChart id="chart" />
        </section>
      </main>
    </div>
  );
}
